CREATE TABLE EMPLOYEE_DEDUCTIONS ( 
EMP_DEDUCTION_ID NUMBER NOT NULL, 
EMPLOYEE_ID NUMBER, 
DEDUCTION_ID NUMBER, 
DEDUCTION_AMOUNT NUMBER(10, 2), -- Fixed amount if 
applicable 
DEDUCTION_PERCENT NUMBER(4, 2)  -- Percentage if applicable 
); 