CREATE TABLE EMPLOYEES ( 
    EMPLOYEE_ID NUMBER NOT NULL, 
    FIRST_NAME VARCHAR2(50), 
    LAST_NAME VARCHAR2(50) NOT NULL, 
    EMAIL VARCHAR2(100), 
    PHONE_NUMBER VARCHAR2(20), 
    HIRE_DATE DATE NOT NULL, 
    JOB_ID VARCHAR2(20), 
    SALARY NUMBER(10, 2), 
    COMMISSION_PCT NUMBER(3, 2), 
    MANAGER_ID NUMBER, 
    DEPARTMENT_ID NUMBER, 
    STATUS_ID NUMBER 
);