CREATE TABLE JOB_HISTORY ( 
    HISTORY_ID NUMBER NOT NULL, 
    EMPLOYEE_ID NUMBER NOT NULL, 
    START_DATE DATE NOT NULL, 
    END_DATE DATE, 
    JOB_ID VARCHAR2(20), 
    DEPARTMENT_ID NUMBER 
); 