CREATE TABLE LEAVE_REQUESTS ( 
    REQUEST_ID NUMBER NOT NULL, 
    EMPLOYEE_ID NUMBER, 
    LEAVE_TYPE_ID NUMBER, 
    START_DATE DATE NOT NULL, 
    END_DATE DATE NOT NULL, 
    REASON VARCHAR2(200), 
    APPROVAL_STATUS VARCHAR2(20) -- e.g., 'Pending', 'Approved' 
);