CREATE TABLE PAYROLL_TRANSACTIONS ( 
TRANSACTION_ID NUMBER NOT NULL, 
EMPLOYEE_ID NUMBER, 
TRANSACTION_DATE DATE NOT NULL, 
PERIOD_START DATE, 
PERIOD_END DATE, 
GROSS_PAY NUMBER(10, 2), 
TOTAL_DEDUCTIONS NUMBER(10, 2), 
NET_PAY NUMBER(10, 2) 
);