-- 1. Link COUNTRIES to REGIONS 
ALTER TABLE COUNTRIES ADD CONSTRAINT FK_COUNTRIES_REGION 
FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID); 
 -- 2. Link LOCATIONS to COUNTRIES 
ALTER TABLE LOCATIONS ADD CONSTRAINT FK_LOCATIONS_COUNTRY 
FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID); 
 -- 3. Link DEPARTMENTS to LOCATIONS 
ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_DEP_LOCATION 
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID); 
 
-- 4. Link EMPLOYEES to JOBS, DEPARTMENTS, and STATUSES 
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMP_JOB 
FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID); 
 
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMP_DEP 
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID); 
 
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMP_STATUS 
FOREIGN KEY (STATUS_ID) REFERENCES STATUSES(STATUS_ID); 
 -- Self-Join: Link EMPLOYEES to EMPLOYEES (for Manager) 
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMP_MANAGER 
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID); 
 -- 5. Link JOB_HISTORY to EMPLOYEES, JOBS, and DEPARTMENTS 
ALTER TABLE JOB_HISTORY ADD CONSTRAINT FK_JH_EMP 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID); 
 
ALTER TABLE JOB_HISTORY ADD CONSTRAINT FK_JH_JOB 
FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID); 
 
ALTER TABLE JOB_HISTORY ADD CONSTRAINT FK_JH_DEP 
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID); 
 -- 6. Link LEAVE_REQUESTS to EMPLOYEES and LEAVE_TYPES 
ALTER TABLE LEAVE_REQUESTS ADD CONSTRAINT FK_LR_EMP 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID); 
 
ALTER TABLE LEAVE_REQUESTS ADD CONSTRAINT FK_LR_TYPE 
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES LEAVE_TYPES(LEAVE_TYPE_ID); 
 -- 7. Link ATTENDANCE_LOGS to EMPLOYEES 
ALTER TABLE ATTENDANCE_LOGS ADD CONSTRAINT FK_ATT_EMP 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID); 
 -- 8. Link EMPLOYEE_DEDUCTIONS to EMPLOYEES and DEDUCTION_TYPES 
ALTER TABLE EMPLOYEE_DEDUCTIONS ADD CONSTRAINT FK_ED_EMP 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID); 
 
ALTER TABLE EMPLOYEE_DEDUCTIONS ADD CONSTRAINT FK_ED_TYPE 
FOREIGN KEY (DEDUCTION_ID) REFERENCES DEDUCTION_TYPES(DEDUCTION_ID); 
 -- 9. Link PAYROLL_TRANSACTIONS to EMPLOYEES 
ALTER TABLE PAYROLL_TRANSACTIONS ADD CONSTRAINT FK_PT_EMP 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);