-- Module A: Location, Organization PKs 
ALTER TABLE REGIONS ADD CONSTRAINT PK_REGIONS PRIMARY KEY (REGION_ID); 
ALTER TABLE COUNTRIES ADD CONSTRAINT PK_COUNTRIES PRIMARY KEY (COUNTRY_ID); 
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID); 
ALTER TABLE DEPARTMENTS ADD CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID); 
 -- Module B: HR Core PKs 
ALTER TABLE JOBS ADD CONSTRAINT PK_JOBS PRIMARY KEY (JOB_ID); 
ALTER TABLE STATUSES ADD CONSTRAINT PK_STATUSES PRIMARY KEY (STATUS_ID); 
ALTER TABLE EMPLOYEES ADD CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID); 
ALTER TABLE JOB_HISTORY ADD CONSTRAINT PK_JOB_HISTORY PRIMARY KEY (HISTORY_ID); 
 -- Module C: Time, Attendance PKs 
ALTER TABLE LEAVE_TYPES ADD CONSTRAINT PK_LEAVE_TYPES PRIMARY KEY (LEAVE_TYPE_ID); 
ALTER TABLE LEAVE_REQUESTS ADD CONSTRAINT PK_LEAVE_REQUESTS PRIMARY KEY (REQUEST_ID); 
ALTER TABLE ATTENDANCE_LOGS ADD CONSTRAINT PK_ATTENDANCE_LOGS PRIMARY KEY (LOG_ID); 
 -- Module D: Payroll PKs 
ALTER TABLE DEDUCTION_TYPES ADD CONSTRAINT PK_DEDUCTION_TYPES PRIMARY KEY 
(DEDUCTION_ID); 
ALTER TABLE EMPLOYEE_DEDUCTIONS ADD CONSTRAINT PK_EMP_DEDUCTIONS PRIMARY KEY 
(EMP_DEDUCTION_ID); 
ALTER TABLE PAYROLL_TRANSACTIONS ADD CONSTRAINT PK_PAYROLL_TRANS PRIMARY KEY 
(TRANSACTION_ID);